language: php
php:
  - 7.3
  - 7.4

services:
  - mysql
  - postgresql

env:
  global:
    - APP_NAME=user_external
    - PHP_COVERAGE=FALSE
  matrix:
  #  - DB=sqlite SERVER=nextcloud/travis_ci/master SERVER_BRANCH=master
    - DB=sqlite SERVER=nextcloud/travis_ci/master SERVER_BRANCH=stable20
    - DB=sqlite SERVER=nextcloud/travis_ci/master SERVER_BRANCH=stable19
  #  - DB=mysql SERVER=nextcloud/travis_ci/master SERVER_BRANCH=master PHP_COVERAGE=TRUE
    - DB=mysql SERVER=nextcloud/travis_ci/master SERVER_BRANCH=stable20 PHP_COVERAGE=TRUE
    - DB=mysql SERVER=nextcloud/travis_ci/master SERVER_BRANCH=stable19 PHP_COVERAGE=TRUE
  #  - DB=pgsql SERVER=nextcloud/travis_ci/master SERVER_BRANCH=master
    - DB=pgsql SERVER=nextcloud/travis_ci/master SERVER_BRANCH=stable20
    - DB=pgsql SERVER=nextcloud/travis_ci/master SERVER_BRANCH=stable19

matrix:
  fast_finish: true

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils
  - wget https://raw.githubusercontent.com/$SERVER/before_install.sh
  - . ./before_install.sh "$APP_NAME" "$SERVER_BRANCH" "$DB"
  - cd ../core || cd ../server
  - php occ app:enable $APP_NAME

before_script:
  # Test lint
  - cd apps/$APP_NAME
  - find . -name \*.php -exec php -l "{}" \;

script:
  # Check info.xml schema validity
  - wget https://apps.nextcloud.com/schema/apps/info.xsd
  - xmllint appinfo/info.xml --schema info.xsd --noout
  - rm info.xsd

  # Run phpunit tests
  # - cd tests
  # - phpunit --configuration configuration.xml

  # Create coverage report
  # - sh -c "if [ '$PHP_COVERAGE' != 'FALSE' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  # - sh -c "if [ '$PHP_COVERAGE' != 'FALSE' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
